### ISSUE TITLE
Testing and CI setup

### ISSUE THREAD

**Issue by divanvisagie** [Nounse/Roadblock#1]
### Description

Set up testing and CI
### Expected outcome

Being able to write and run karma tests and having travis automatically run them

### Tasks
- [x] Set up travis CI 
- [x] Set up karma tests
- [x] Test the first element

**Comment by divanvisagie** [comment]
Did a merge on some groundwork at https://github.com/Nounse/Roadblock/pull/7
Still need to do some component testing and add firefox as a browser to test against
