### ISSUE TITLE
Add Authentication

### ISSUE THREAD

**Issue by divanvisagie** [Nounse/Roadblock#3]
### Description
Create authentication functionality and login screen

### Expected outcome
Application is not accessible if user is not logged in

### Tasks
- [ ] Create Login screen 
- [ ] Integrate with firebase authentication
- [ ] User is blocked by login screen if not authenticated
